# Generated by Django 3.1.3 on 2024-05-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
